name: NPM Script

on:
  workflow_call:
    inputs:
      artifact-retention-days:
        default: 5
        description: 'Artifact retention in days'
        type: number
        required: false
      artifact-name:
        description: Artifact name. Requires `artifact-path`.
        required: false
        type: string
      artifact-path:
        description: Artifact path. Requires `artifact-name`.
        required: false
        type: string
      cache-dependency-path:
        default: ./package-lock.json
        description: 'Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. It will generate hash from the target file for primary key. It works only If cache is specified. Supports wildcards or a list of file names for caching multiple dependencies.'
        type: string
      script:
        description: NPM script to run. Value will be used like `npm run <value>`
        required: true
        type: string

jobs:
  npm-run:
    name: NPM Run "${{inputs.script}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          cache-dependency-path: ${{inputs.cache-dependency-path}}

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ./node-modules
          key: modules-${{ hashFiles(inputs.cache-dependency-path) }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Run Script
        run: |
          npm run ${{inputs.script}}

      - name: Upload Artifact
        if: ${{ inputs.artifact-name && inputs.artifact-path }}
        uses: actions/upload-artifact@v4
        with:
          retention-days: ${{ inputs.artifact-retention-days }}
          path: ${{ inputs.artifact-path }}
          name: ${{ inputs.artifact-name }}
