name: Semantic Release

on:
  workflow_call:
    inputs:
      artifact-name-1:
        description: Artifact name (1) Requires `artifact-path-1`.
        required: false
        type: string
      artifact-path-1:
        description: Artifact path (1) Requires `artifact-name-1`.
        required: false
        type: string
      artifact-name-2:
        description: Artifact name (2) Requires `artifact-path-2`.
        required: false
        type: string
      artifact-path-2:
        description: Artifact path (2) Requires `artifact-name-2`.
        required: false
        type: string
      artifact-name-3:
        description: Artifact name (3) Requires `artifact-path-3`.
        required: false
        type: string
      artifact-path-3:
        description: Artifact path (3) Requires `artifact-name-3`.
        required: false
        type: string
      dry_run:
        default: false
        description: Whether to run semantic release in dry-run mode. It will override the dryRun attribute in your configuration file
        type: boolean
        required: false
    outputs:
      version:
        description: "Version created by semantic-release"
        value: ${{ jobs.semantic-release.outputs.version }}
      published:
        description: "Whether a new release was published. The return value is in the form of a string. (`\"true\"` or `\"false\"`)"
        value: ${{ jobs.semantic-release.outputs.published }}

jobs:
  semantic-release:
    name: Semantic Release
    permissions:
      contents: write # Publish GitHub release
      pull-requests: write # Comment on released pull requests
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Download Artifact (1)
      if: ${{ inputs.artifact-name-1 && inputs.artifact-path-1 }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name-1 }}
        path: ${{ inputs.artifact-path-1 }}

    - name: Download Artifact (2)
      if: ${{ inputs.artifact-name-2 && inputs.artifact-path-2 }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name-2 }}
        path: ${{ inputs.artifact-path-2 }}

    - name: Download Artifact (3)
      if: ${{ inputs.artifact-name-3 && inputs.artifact-path-3 }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name-3 }}
        path: ${{ inputs.artifact-path-3 }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      with:
        dry_run: ${{ inputs.dry_run }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HUSKY: 0

    - name: Job Summary
      env:
        VERSION: ${{steps.semantic.outputs.new_release_version}}
      run: |
        if [[ -z "$VERSION" ]]; then
          echo "### No new version needed" >> $GITHUB_STEP_SUMMARY
        else
          echo "### New Version > $VERSION" >> $GITHUB_STEP_SUMMARY
          if "${{ inputs.dry_run }}"; then
            echo "(not yet created because this was a dry_run)" >> $GITHUB_STEP_SUMMARY
          fi
        fi
